### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by A55adon** [NorthernMan54/JC3248W535EN#4]
### Analysis

At the beginning of the build process I get this error message
UnknownPackageError: Could not find the package with 'platformio/framework-espidf @ 3.50105.0' requirements for your system 'windows_amd64'", why?

### Expected Behavior

Succesfull build process

### Steps To Reproduce

Download the repository and presss build from platformio

### Logs

```markdown
*  Executing task: C:\Users\simon\.platformio\penv\Scripts\platformio.exe run --target upload 

Processing LVGL-320-480 (platform: espressif32; board: 320x480; framework: espidf)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Tool Manager: Installing platformio/framework-espidf @ 3.50105.0
UnknownPackageError: Could not find the package with 'platformio/framework-espidf @ 3.50105.0' requirements for your system 'windows_amd64'

 *  The terminal process "C:\Users\simon\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

### Configuration

```json
Standard configuration with vscode
```

### Environment

- OS: win11
- Software: vscode

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
This likely would be a challenge with that package and not this library. I'm coding on Mac, so can't offer any more than this.

**Comment by A55adon** [comment]
Okay thanks
